#!/bin/sh

python3 -m venv .env
. .env/bin/activate
pip install --upgrade pip
pip install -r $PWD/gdex-doc-gen/requirements.txt
$PWD/gdex-doc-gen/generator.py -project_name "Godot RmlUi" -src_folder ./doc_classes -dst_folder ./
deactivate